apiVersion: v1
kind: Service
metadata:
  name: cassandra-svc
  namespace: cassandra
  labels:
    app: cassandra
spec:
  ports:
  - name: http
    nodePort: 27826
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    app: cassandra
  type: NodePort
