apiVersion: v1
kind: ReplicationController
metadata:
  name: cassandra
  namespace: cassandra
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: touch20032003/cassandra-xy:0.1
        ports:
        - containerPort: 9042
        - containerPort: 9042
      #imagePullSecrets:
       #- name: docker-registry-secret
      #nodeSelector:
        #tooltype: jmeter
